# Generated by AI

from pathlib import Path
from PIL import Image
import numpy as np
from features_comparator import *

def find_invalid_images(n):
    paths = find_paths(n)
    invalid = []

    for path in paths:
        try:
            with Image.open(path) as img:
                width, height = img.size

            if width != 1800 and height != 1800:
                invalid.append(path)

        except Exception as e:
            print(f"Error reading {path}: {e}")

    return invalid

def remove_images(image_paths):
    deleted = 0

    for path in image_paths:
        try:
            Path(path).unlink()
            deleted += 1
        except FileNotFoundError:
            print(f"File not found: {path}")
        except Exception as e:
            print(f"Error deleting {path}: {e}")

    return deleted

invalid_imagesPaths = find_invalid_images(14553)
remove_images(invalid_imagesPaths)
