# -*- coding: utf-8 -*-
"""circum_sphere

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YncydsXf5p5nAbBU8vn3qlouo82Y8f18
"""

import numpy as np
from scipy.spatial import Delaunay
from scipy.spatial import distance

# (3D)
# Open the file and read the vertices as strings
with open("/mnt/c/Users/moham/OneDrive/Desktop/Cours/2A/IMA/Vision 3D video/IMA208TP/Bimba.xyz", "r") as f:
    vertex_strings = f.readlines()

# Convert the vertex strings to a NumPy array of shape (N, 3)
points3D = np.zeros((len(vertex_strings), 3))
for i, vertex_str in enumerate(vertex_strings):
    vertex_arr = [float(coord) for coord in vertex_str.strip().split()]
    points3D[i] = vertex_arr


tri = Delaunay(points3D)

def circumsphere(p1, p2, p3, p4):
    """Gets the center and radius of the corresponding tetrahedra.
    This solves the equation : 2*(p_i-p_1)x_i = (||p_i||^2-||p_1||^2)/2 for i in [2,3,4]"""
    A = np.array([p2 - p1, p3 - p1, p4 - p1]).T
    b  = np.array([
        np.dot(p2, p2) - np.dot(p1, p1),
        np.dot(p3, p3) - np.dot(p1, p1),
        np.dot(p4, p4) - np.dot(p1, p1),
    ]) / 2.0

    center = np.linalg.solve(A, b) + p1 #since we are solving for C'=C-p1
    radius = np.linalg.norm(center - p1)
    return center, radius

def alpha_shape_surface(points: np.ndarray, alpha: float) -> np.ndarray:
    tri = Delaunay(points)
    simplices = tri.simplices       
    neighbors = tri.neighbors         
 
    radii = np.array([
        circumsphere(points[s[0]], points[s[1]], points[s[2]], points[s[3]])[1]
        for s in simplices
    ])
 
    kept = radii <= alpha
    print(f" {kept.sum()} / {len(simplices)} tetrahedra kept for alpha = {alpha}.")
    triangles = []
    face_indices = [(1, 2, 3), (0, 2, 3), (0, 1, 3), (0, 1, 2)]
 
    for i, simplex in enumerate(simplices):
        if not kept[i]:
            continue
        for j, face in enumerate(face_indices):
            neighbor_idx = neighbors[i, j]
            # boundary face: neighbor not kept, or outside convex hull
            if neighbor_idx == -1 or not kept[neighbor_idx]:
                tri_verts = points[list(simplex[k] for k in face)]
                triangles.append(tri_verts)
 
    return np.array(triangles) if triangles else np.empty((0, 3, 3))

# Q1. Automatically finding the best alpha
def auto_alpha(points: np.ndarray, percentile: float = 10.0) -> float:
    tri = Delaunay(points)
    radii = np.array([
        circumsphere(points[s[0]], points[s[1]], points[s[2]], points[s[3]])[1]
        for s in tri.simplices
    ])
    finite_radii = radii[np.isfinite(radii)]
    alpha = float(np.percentile(finite_radii, percentile))
    return alpha

def local_density_alpha(points: np.ndarray, k: int = 10, scale: float = 2.0) -> np.ndarray:
    from scipy.spatial import cKDTree
 
    tree = cKDTree(points)
    # query k+1 because the point itself is the first result
    dists, _ = tree.query(points, k=k + 1)
    mean_knn_dist = dists[:, 1:].mean(axis=1)   # exclude self-distance
    per_point_alpha = scale * mean_knn_dist
    return per_point_alpha
 
# Q2. for varying-density point clouds
from scipy.spatial.distance import pdist

def adaptive_alpha_shape_surface(points: np.ndarray, k: int = 15, scale: float = 3.5) -> np.ndarray:
    """
    Adaptive alpha shape using Maximum Edge Length instead of Circumsphere Radius.
    """
    # 1. Calculate base density (k=15 provides a smoother neighborhood)
    # Scale of 3.0 to 4.0 is usually the sweet spot for edge-length filtering
    per_point_alpha = local_density_alpha(points, k=k, scale=scale)
    
    tri = Delaunay(points)
    simplices = tri.simplices
    neighbors = tri.neighbors
    
    kept = np.zeros(len(simplices), dtype=bool)
    
    for i, s in enumerate(simplices):
        # Get the 3D coordinates of the 4 vertices of the tetrahedron
        tetra_pts = points[s]
        
        # Calculate the 6 edge lengths of the tetrahedron and find the longest one
        max_edge = pdist(tetra_pts).max()
        
        # Use max() of the 4 vertices' local densities to prevent tearing
        local_alpha = per_point_alpha[s].max()
        
        # Keep if the longest edge is smaller than the local threshold
        kept[i] = max_edge <= local_alpha
        
    print(f"Adaptive filter (Edge Method): {kept.sum()} / {len(simplices)} tetrahedra kept.")
    
    # --- Face Extraction (Unchanged) ---
    triangles = []
    for i, simplex in enumerate(simplices):
        if not kept[i]:
            continue
        for j, face in enumerate(FACE_INDICES):
            neighbor_idx = neighbors[i, j]
            if neighbor_idx == -1 or not kept[neighbor_idx]:
                v0, v1, v2 = points[simplex[list(face)]]
                opposite_vert = points[simplex[j]]
                
                n = np.cross(v1 - v0, v2 - v0)
                if np.dot(n, v0 - opposite_vert) < 0:
                    triangles.append(np.array([v0, v2, v1]))
                else:
                    triangles.append(np.array([v0, v1, v2]))
                    
    return np.array(triangles) if triangles else np.empty((0, 3, 3))

FACE_INDICES = [(1,2,3), (0,2,3), (0,1,3), (0,1,2)]

def triangle_normal(v0, v1, v2):
    """Normal of a triangle, used for stl writing."""
    n = np.cross(v1 - v0, v2 - v0)
    norm = np.linalg.norm(n)
    if norm == 0:
        return np.zeros(3)
    return n / norm

def write_stl(triangles, path, name="mesh"):
    with open(path, "w") as f:
        f.write(f"solid {name}\n")
        for triangle in triangles:
            v0, v1, v2 = triangle[0], triangle[1], triangle[2]
            n = triangle_normal(v0, v1, v2)
            f.write(f"  facet normal {n[0]:.6e} {n[1]:.6e} {n[2]:.6e}\n")
            f.write( "    outer loop\n")
            f.write(f"      vertex {v0[0]:.6e} {v0[1]:.6e} {v0[2]:.6e}\n")
            f.write(f"      vertex {v1[0]:.6e} {v1[1]:.6e} {v1[2]:.6e}\n")
            f.write(f"      vertex {v2[0]:.6e} {v2[1]:.6e} {v2[2]:.6e}\n")
            f.write( "    endloop\n")
            f.write( "  endfacet\n")
        f.write(f"endsolid {name}\n")
    print(f"STL written → {path}")

tri_alpha_shape=alpha_shape_surface(points3D, alpha=0.2)
write_stl(tri_alpha_shape, "alpha_shape.stl", "regular_alpha_shape")

tri_adaptive_alpha_shape=adaptive_alpha_shape_surface(points3D, k=10, scale=2)
write_stl(tri_adaptive_alpha_shape, "adaptive_alpha_shape.stl", "adaptive_alpha_shape")