# -*- coding: utf-8 -*-
"""circum_sphere

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YncydsXf5p5nAbBU8vn3qlouo82Y8f18
"""

import numpy as np
from scipy.spatial import Delaunay
from scipy.spatial import distance

# (3D)
# Open the file and read the vertices as strings
with open("/mnt/c/Users/moham/OneDrive/Desktop/Cours/2A/IMA/Vision 3D video/IMA208TP/Bunny.xyz", "r") as f:
    vertex_strings = f.readlines()

def write_stl(path, points, faces):
    header = "solid delaunay_mesh"
    with open(path, "wb") as f:
        f.write(header)
        for (i,j,k) in faces:
            p1,p2,p3 = points[i], points[j], points[k]
            n=triangle_normal(i,j,k)
            f.write(f"  facet normal {n[0]} {n[1]} {n[2]}\n")
            f.write("    outer loop\n")
            f.write(f"      vertex {p1[0]} {p1[1]} {p1[2]}\n")
            f.write(f"      vertex {p2[0]} {p2[1]} {p2[2]}\n")
            f.write(f"      vertex {p3[0]} {p3[1]} {p3[2]}\n")
            f.write("    endloop\n")
            f.write("  endfacet\n") 
        f.write("endsolid delaunay_mesh\n")
    pass

# Convert the vertex strings to a NumPy array of shape (N, 3)
points3D = np.zeros((len(vertex_strings), 3))
for i, vertex_str in enumerate(vertex_strings):
    vertex_arr = [float(coord) for coord in vertex_str.strip().split()]
    points3D[i] = vertex_arr


tri = Delaunay(points3D)

def circumsphere(p1, p2, p3, p4):
    A = np.array([p2 - p1, p3 - p1, p4 - p1]).T
    b = np.array([
        np.dot(p2 - p1, p2 - p1),
        np.dot(p3 - p1, p3 - p1),
        np.dot(p4 - p1, p4 - p1)
    ]) / 2.0

    center = np.linalg.solve(A, b) + p1 #since we are solving for C'=C-p1
    radius = np.linalg.norm(center - p1)
    return center, radius

def is_delaunay_tetra(points, tetra):
    p1, p2, p3, p4 = points[tetra]
    center, radius = circumsphere(p1, p2, p3, p4)

    # Check all other points
    for i in range(len(points)):
        if i not in tetra:
            if np.linalg.norm(points[i] - center) < radius:
                return False  
    return True

filtered_simplices = []
for tetra in tri.simplices:
    if is_delaunay_tetra(points3D, tetra):
        print("Delaunay tetra:", tetra)
        filtered_simplices.append(tetra)

filtered_simplices = np.array(filtered_simplices)
from collections import Counter

faces = []
for tet in filtered_simplices:
    i, j, k, l = tet
    faces.extend([
        tuple(sorted((i, j, k))),
        tuple(sorted((i, j, l))),
        tuple(sorted((i, k, l))),
        tuple(sorted((j, k, l))),
    ])

face_counts = Counter(faces)
boundary_faces = [f for f in faces if face_counts[f] == 1]

def triangle_normal(p1, p2, p3):
    v1 = p2 - p1
    v2 = p3 - p1
    n = np.cross(v1, v2)
    norm = np.linalg.norm(n)
    if norm == 0:
        return np.array([0.0, 0.0, 0.0])
    return n / norm


write_stl("bunny_delaunay.stl", points3D, boundary_faces)
