# -*- coding: utf-8 -*-
"""circum_sphere

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YncydsXf5p5nAbBU8vn3qlouo82Y8f18
"""

import numpy as np
from scipy.spatial import Delaunay
from scipy.spatial import distance

# (3D)
# Open the file and read the vertices as strings
with open("/mnt/c/Users/moham/OneDrive/Desktop/Cours/2A/IMA/Vision 3D video/IMA208TP/Bunny.xyz", "r") as f:
    vertex_strings = f.readlines()

# Convert the vertex strings to a NumPy array of shape (N, 3)
points3D = np.zeros((len(vertex_strings), 3))
for i, vertex_str in enumerate(vertex_strings):
    vertex_arr = [float(coord) for coord in vertex_str.strip().split()]
    points3D[i] = vertex_arr


tri = Delaunay(points3D)

def circumsphere(tetra):
    """Gets the center and radius of the corresponding tetrahedra.
    This solves the equation : 2*(p_i-p_1)x_i = (||p_i||^2-||p_1||^2)/2 for i in [2,3,4]"""
    p1, p2, p3, p4 = tetra
    A = np.array([p2 - p1, p3 - p1, p4 - p1]).T
    b  = np.array([
        np.dot(p2, p2) - np.dot(p1, p1),
        np.dot(p3, p3) - np.dot(p1, p1),
        np.dot(p4, p4) - np.dot(p1, p1),
    ]) / 2.0

    center = np.linalg.solve(A, b) + p1 #since we are solving for C'=C-p1
    radius = np.linalg.norm(center - p1)
    return center, radius

bbox_diag = np.linalg.norm(points3D.max(axis=0) - points3D.min(axis=0))
alpha = bbox_diag *0.1   # threshold
print(f"Threshold used : {alpha:.4f}")

kept_tetrahedra = []
for tet in tri.simplices:
    tet_pts = points3D[tet]          # shape (4, 3)
    c, r = circumsphere(tet_pts)
    if r <= alpha:
        kept_tetrahedra.append(tet)
print(f"After filtering, number of tetrahedras : {len(kept_tetrahedra)}")     

# Recover triangles from tetrahedra
FACE_INDICES = [(1,2,3), (0,2,3), (0,1,3), (0,1,2)]

def triangle_normal(v0, v1, v2):
    """Normal of a triangle, used for stl writing."""
    n = np.cross(v1 - v0, v2 - v0)
    norm = np.linalg.norm(n)
    if norm == 0:
        return np.zeros(3)
    return n / norm

def write_stl_filtered_delaunay():
    output_path = "bunny_delaunay.stl"
    with open(output_path, "w") as stl:
        stl.write("solid delaunay_bunny\n")

        for tet in kept_tetrahedra:
            for fi in FACE_INDICES:
                v0 = points3D[tet[fi[0]]]
                v1 = points3D[tet[fi[1]]]
                v2 = points3D[tet[fi[2]]]
                n  = triangle_normal(v0, v1, v2)

                stl.write(f"  facet normal {n[0]:.6e} {n[1]:.6e} {n[2]:.6e}\n")
                stl.write( "    outer loop\n")
                stl.write(f"      vertex {v0[0]:.6e} {v0[1]:.6e} {v0[2]:.6e}\n")
                stl.write(f"      vertex {v1[0]:.6e} {v1[1]:.6e} {v1[2]:.6e}\n")
                stl.write(f"      vertex {v2[0]:.6e} {v2[1]:.6e} {v2[2]:.6e}\n")
                stl.write( "    endloop\n")
                stl.write( "  endfacet\n")

        stl.write("endsolid delaunay_bunny\n")

write_stl_filtered_delaunay()

# Q1. Automatically finding the alpha  -----------------------------------------------------------
all_radiusses = np.array([circumsphere(points3D[tet])[1] for tet in tri.simplices])
def find_auto_alpha(radii, jump_factor=5.0):
    """
      - Sort all radiuses.
      - Compute the ratio between each consecutive pair (r[i+1] / r[i]).
      - Select the first ratio where ratio>jump_factor.

    jump_factor: how many times larger the next radius must be to count.
    """
    finite = radii[np.isfinite(radii)]
    sorted_r = np.sort(finite)

    ratios = sorted_r[1:] / (sorted_r[:-1] + 1e-12)

    jump_indices = np.where(ratios > jump_factor)[0]

    if len(jump_indices) == 0:
        # No clear jump → fall back to 10th percentile
        alpha = np.percentile(sorted_r, 10)
        print(f"[Auto alpha] No jump found, using 10th percentile: {alpha:.5f}")
    else:
        # Cut at the value just BEFORE the first big jump
        cut = jump_indices[0]
        alpha = sorted_r[cut]
        print(f"Found alpha = {alpha:.5f}")

    return alpha

auto_alpha = find_auto_alpha(all_radiusses)
kept_global = [tet for tet, r in zip(tri.simplices, all_radiusses) if r <= auto_alpha]
print(f"[Global] Kept {len(kept_global)} / {len(tri.simplices)} tetrahedra\n")

# Q2. for Varying-density point clouds 

def compute_local_scale(points, k=10):
    """
    For each point, estimate the mean distance to its k nearest neighbors.

    Returns : an array of shape (N,)
    """
    dist_matrix = distance.cdist(points, points)
    partitioned = np.partition(dist_matrix, k + 1, axis=1)
    mean_nn_dist = partitioned[:, 1:k + 1].mean(axis=1)

    return mean_nn_dist

def adaptive_alpha_filter(simplices, points, local_scale, scale_factor=3.0):
    """
    For each tetrahedron, its threshold = scale_factor × (mean local scale
    of its 4 vertices). 
    """
    kept = []
    for tet, r in zip(simplices, all_radiusses):
        if not np.isfinite(r):
            continue
        local_alpha = scale_factor * local_scale[tet].mean()
        if r <= local_alpha:
            kept.append(tet)
    return kept

local_scale = compute_local_scale(points3D, k=10)
print(f"Local scale — min: {local_scale.min():.5f}  "
      f"max: {local_scale.max():.5f}  "
      f"mean: {local_scale.mean():.5f}")

kept_adaptive = adaptive_alpha_filter(tri.simplices, points3D, local_scale, scale_factor=3.0)
print(f"[Adaptive] Kept {len(kept_adaptive)} / {len(tri.simplices)} tetrahedra\n")

FACE_INDICES = [(1, 2, 3), (0, 2, 3), (0, 1, 3), (0, 1, 2)]

def triangle_normal(v0, v1, v2):
    n = np.cross(v1 - v0, v2 - v0)
    norm = np.linalg.norm(n)
    return n / norm if norm > 0 else np.zeros(3)

def write_stl(tetrahedra, points, path, name="mesh"):
    with open(path, "w") as f:
        f.write(f"solid {name}\n")
        for tet in tetrahedra:
            for fi in FACE_INDICES:
                v0, v1, v2 = points[tet[fi[0]]], points[tet[fi[1]]], points[tet[fi[2]]]
                n = triangle_normal(v0, v1, v2)
                f.write(f"  facet normal {n[0]:.6e} {n[1]:.6e} {n[2]:.6e}\n")
                f.write( "    outer loop\n")
                f.write(f"      vertex {v0[0]:.6e} {v0[1]:.6e} {v0[2]:.6e}\n")
                f.write(f"      vertex {v1[0]:.6e} {v1[1]:.6e} {v1[2]:.6e}\n")
                f.write(f"      vertex {v2[0]:.6e} {v2[1]:.6e} {v2[2]:.6e}\n")
                f.write( "    endloop\n")
                f.write( "  endfacet\n")
        f.write(f"endsolid {name}\n")
    print(f"STL written → {path}")

write_stl(kept_global,   points3D, "bunny_global_alpha.stl",   "global_alpha")
write_stl(kept_adaptive, points3D, "bunny_adaptive_alpha.stl", "adaptive_alpha")